// Generated by CoffeeScript 1.10.0
(function() {
  window.showExample = function(exampleName, targetElement) {
    if (exampleName === "") {

    } else if (exampleName === "Method Type Invocation") {
      return targetElement.value = "// Define method Ident\nIdent: at least {\n\	p: T\n\	result: T\n\	result = p\n}\n\n// Call method Ident\nx: T\n{ p = x } & Ident . new . result\n";
    } else if (exampleName === "WIP-1") {
      return targetElement.value = "X: {\n\	Y: {\n\		x:X\n\		x = Y.new\n\	}\n\	x:X\n}\n\nx:X\nX.new.x = x\nX.new.Y | {\n\	x: X\n\	x\n}.new\n";
    } else {
      return alert("Unknown example name '" + exampleName + "'");
    }
  };

}).call(this);
